eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
okta:
  oauth2:
    audience: api://default
    issuer: https://dev-30721635.okta.com/oauth2/default
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
