eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka
okta:
  oauth2:
    audience: api://default
    issuer: https://dev-30721635.okta.com/oauth2/default
